name: Build and push Mlflow docker

on:
  push:
    branches:
      - main
    
    paths:
      - 'Dockerfile'
      
    permissions:
      contents: read
      id-token: write


    jobs:
      build-mlflow-image:
        runs-on: ubuntu-latest
      
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        -name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws-region: us-west-2

          -name: Login to ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

          -uses: actions/setup-python@v2
          with:
            python-version: '3.8'

            -name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

              -name: Build and push Mlflow image

              run:
                  cd docker/mlflow
                  bash mlflow_pyfunc.sh


