name: Build and push docker images

on:
  push:
    branches:
      - main
    
    paths:
      - 'Dockerfile'
      - 'src/**'
      - '.github/workflows/build-images.yaml'


    permissions:
      contents: read
      id-token: write

    jobs:
      build-images:
        runs-on: ubuntu-latest
      

      strategy:
        fail-fast: false

        matrix:
        include:
          -folder:docker/processing/
          repository:hosuing-processing

          -folder:docker/processing/
          repository:hosuing-processing

        steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Build and push training image
            uses:  composite-action/docker-build-push@v1

            with:
              username: ${{secrets.DOCKER_USERNAME}}
              password: ${{secrets.DOCKER_PASSWORD}}
              repository: ${{matrix.repository}}
              tags: latest
              folder: ${{matrix.folder}}
              push: true